apps/book_reviews/urls.py
from django.conf.urls import url
from . import views

app_name = 'book_reviews'
urlpatterns = [
    url(r'^books/user(?P<id>\d+)$', views.index, name='index'),
    url(r'^add$', views.add, name='add'),
    url(r'^addBook$', views.addBook, name='addBook'),
    url(r'^book/(?P<id>\d+)$', views.book, name='book'),
    url(r'^delete/(?P<id>\d+)$', views.delete, name='delete'),
    url(r'^addReview/(?P<id>\d+)$', views.addReview, name='addReview'),
]

apps/book_reviews/models.py
from __future__ import unicode_literals

from django.db import models
from ..login_reg.models import User

# Create your models here.
class BookManager(models.Manager):
    def create(self, postData):
        title = postData['title']
        alerts = []

        # try:
        #     book = Book.objects.get(title=title)
        # except:
        #     print ('BOOK ALREADY IN DATABASE')
        #     return (False, 'exists')
        #     # print (book.id)
        #     # return (False, 'exists', book.id)
        # else:
        if len(title) < 1:
            alerts.append('Book title cannot be left blank.')
        if len(postData['authorAdd']) < 1:
            alerts.append('Author cannot be left blank.')
        if len(postData['review']) < 1:
            alerts.append('Review cannot be left blank.')
        if postData['rating'] == 'blank':
            alerts.append('Rating cannot be left blank.')

        if alerts:
            print ('FAILED VALIDATION')
            return (False, alerts)

        else:
            user = User.objects.get(id=int(postData['userID']))
            print(user.id, user.first_name)
            book = Book.objects.create(title=postData['title'], author=postData['authorAdd'])
            print(book.title, book.author)
            this_review = Review.objects.create(book=book, review=postData['review'], rating=postData['rating'])
            print(this_review.review, this_review.rating)

            Reviewer.objects.create(user=user, book=book, review=this_review)
            return (True, 'success', book.id)

    def additional(self, postData):
        alerts = []
        if len(postData['review']) < 1:
            alerts.append('Review cannot be left blank.')
        if postData['rating'] == 'blank':
            alerts.append('Rating cannot be left blank.')

        if alerts:
            return (False, alerts)

        else:
            user = User.objects.get(id=postData['userID'])
            book = Book.objects.get(id=postData['bookID'])
            this_review = Review.objects.create(book=book, review=postData['review'], rating=postData['rating'])

            Reviewer.objects.create(user=user, book=book, review=this_review)
            return (True, 'success')

class Book(models.Model):
    title = models.CharField(max_length=500)
    author = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    bookManager = BookManager()
    objects = models.Manager()

class Review(models.Model):
    review = models.TextField(max_length=1000)
    rating = models.PositiveSmallIntegerField()
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Reviewer(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    book = models.ForeignKey(Book, on_delete=models.CASCADE, default=1)
    review = models.ForeignKey(Review, on_delete=models.CASCADE, default=1)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

apps/book_reviews/views.py
from django.shortcuts import render, redirect, HttpResponse
from django.core.urlresolvers import reverse
from django.contrib import messages
from .models import Book, Review, Reviewer, User

# Create your views here.
def index(request, id):
    print(id)
    context = {
        'user':User.objects.get(id=id),
        'books':Book.objects.all(),
        'reviews':Review.objects.all(),
        'reviewers':Reviewer.objects.all()
    }
    return render(request, 'book_reviews/index.html', context)

def add(request):
    # Book.objects.all().delete()
    return render(request, 'book_reviews/addBook.html')

def addBook(request):
    if request.method == "POST":
        verify = Book.bookManager.create(request.POST)

        if verify[0] == False:
            if verify[1] == 'exists':
                print ('nope')
                return HttpResponse('book exists')
            else:
                for alert in verify[1]:
                    messages.add_message(request, messages.INFO, alert)
                return redirect(reverse('book_reviews:add'))

        elif verify[0] == True:
            id = verify[2]
            return redirect(reverse('book_reviews:book', kwargs={'id':id}))

def addReview(request, id):
    if request.method == "POST":
        verify = Book.bookManager.additional(request.POST)

        if verify[0] == False:
            for alert in verify[1]:
                messages.add_message(request, messages.INFO, alert)
            return redirect(reverse('book_reviews:book', kwargs={'id':id}))

        elif verify[0] == True:
            return redirect(reverse('book_reviews:book', kwargs={'id':id}))


def book(request, id):
    context = {
        'book':Book.objects.get(id=id),
        'reviews':Review.objects.all(),
        'reviewers':Reviewer.objects.all()
    }
    return render(request, 'book_reviews/book.html', context)

def delete(request, id):
    if request.method == "GET":
        this_review = Review.objects.get(id=id)
        # delete = Review.objects.get(id=id)
        bookID = this_review.book.id
        print(bookID)
        print ('review id:', id)

        return HttpResponse('delete review function')

apps/book_reviews/templates/book_reviews/addBook.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <title>Book Reviews</title>
    <meta name="description" content="Coding Dojo, Python II, Django II, Belt Reviewer Assignment">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'book_reviews/css/style.css' %}" media="screen">
  </head>
  <body>
    <div class="container" style="width:50%">
      <nav>
        <a class="btn btn-link" href="{% url 'book_reviews:index' request.session.userID %}" role="button">Back</a>
      </nav>

      <header class="page-header">
        <h1>New Reviews <small> add a new book and a review</small></h1>
      </header>

      <!-- {{ request.session.userID }} -->
<!-- messages section -->
      <section>
        {% if messages %}
        <div class="alert alert-danger">
          {% for alert in messages %}
            <p {% if messages.tags %} class="messages.tags" {% endif %}>{{ alert }}</p>
          {% endfor %}
        </div>
        {% endif %}
      </section>

      <section>
        <form action="{% url 'book_reviews:addBook' %}" method="POST">
        {% csrf_token %}
        <input type="hidden" value="{{ request.session.userID }}" name="userID">
        <div class="form-group">
          <label for="inputTitle">Book Title:</label>
          <input class="form-control" type="text" name="title">
        </div>

        <div class="form-group">
          <label>Author:</label>
          <!-- <div class="form-group">
            <label for="inputAuthorSelect">Choose from the list:</label>
            <select class="form-control" name="authorSelect">
              <<option value="blank">Select</option>
              {% for author in authors %}
                <option value="{{ author.id }}">{{ author.name }}</option>
              {% endfor %}
            </select>
          </div> -->

          <div class="form-group">
            <label for="inputAuthorAdd">Or add a new author:</label>
            <input class="form-control" type="text" name="authorAdd">
          </div>
        </div>

        <div class="form-group">
          <label for="inputReview">Review:</label>
          <textarea class="form-control" rows="3" name="review"></textarea>
        </div>

        <div class="form-group">
          <label for="inputRating">Rating:
            <select class="form-control" name="rating">
              <option value="blank"></option>
              <option value="1">1</option>
              <option value="2">2</option>
              <option value="3">3</option>
              <option value="4">4</option>
              <option value="5">5</option>
            </select>
             stars.</label>
        </div>

        <div class="form-group">
          <input class="btn btn-primary" type="submit" value="Add Book and Review">
        </div>
      </section>
      {% for reviewer in reviewers %}
        <p>{{ reviewer.user.id }} {{ reviewer.user.first_name }} {{ reviewer.book.title }}</p>
      {% endfor %}

    </div>
  </body>
</html>

apps/book_reviews/templates/book_reviews/book.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <title>Book Reviews</title>
    <meta name="description" content="Coding Dojo, Python II, Django II, Belt Reviewer Assignment">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'book_reviews/css/style.css' %}" media="screen">
  </head>
  <body>
    <div class="container">
      <nav>
          <a class="btn btn-link" href="{% url 'book_reviews:index' request.session.userID %}" role="button">Home</a>
        </form>
      </nav>
      <header class="page-header">
        <h1>{{ book.title }} <small>by {{ book.author }}</small></h1>
      </header>

      <section class="split">
        <h3>Reviews:</h3>
        {% for reviewer in reviewers %}
          {% if reviewer.book.id == book.id %}
            <article style="display:block;">
              <p>Rating: {{ reviewer.review.rating }} <span class="glyphicon glyphicon-star" aria-hidden="true"></span>'s</p>
              <p><a style="text-decoration:underline;" href="">{{ reviewer.user.first_name }}</a> says: {{ reviewer.review.review }}</p>
              <p>
                Posted on {{ reviewer.review.created_at }}
                {% if reviewer.user.id == request.session.userID %}
                  <a class="btn btn-link" href="{% url 'book_reviews:delete' reviewer.review.id %}" role="button">Delete this Review</a>
                {% endif %}
              </p>
            </article>
          {% endif %}
        {% endfor %}
      </section>

      <section class="split">
        <h3>Add a review for this book</h3>
        {% if messages %}
          <div class="alert alert-danger">
            {% for alert in messages %}
              <p {% if messages.tags %} class="messages.tags" {% endif %}>{{ alert }}</p>
            {% endfor %}
          </div>
        {% endif %}
        <form action="{% url 'book_reviews:addReview' book.id %}" method="POST">
          {% csrf_token %}
          <input type="hidden" value="{{ request.session.userID }}" name="userID">
          <input type="hidden" value="{{ book.id }}" name="bookID">
          <div class="form-group">
            <textarea class="form-control" rows="3" name="review"></textarea>
          </div>

          <div class="form-group">
            <label for="inputRating">Rating:
              <select class="form-control" name="rating">
                <option value="blank"></option>
                <option value="1">1</option>
                <option value="2">2</option>
                <option value="3">3</option>
                <option value="4">4</option>
                <option value="5">5</option>
              </select>
               stars.
             </label>
          </div>

          <div class="form-group">
            <input class="btn btn-primary" type="submit" value="Submit Review">
          </div>
        </form>
      </section>

    </div>
  </body>
</html>

apps/book_reviews/templates/book_reviews/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <title>Book Reviews</title>
    <meta name="description" content="Coding Dojo, Python II, Django II, Belt Reviewer Assignment">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'book_reviews/css/style.css' %}">
  </head>
  <body>
    <div class="container">
      <nav>
        <form action="{% url 'login_reg:delete' user.id %}" method="POST">
          <a class="btn btn-link" href="{% url 'book_reviews:add' %}" role="button">Add Book and Review</a>
          {% csrf_token %}
          <input class="btn btn-link" type="submit" value="Delete Account">
          <a class="btn btn-link" href="{% url 'login_reg:logout' %}" role="button">Logout</a>
        </form>
      </nav>
      <header class="page-header">
        <h1>Book Reviews <small>Home Page</small></h1>
      </header>

      <section>
        {% if request.session.success %}
          <h3>Welcome {{ request.session.success }}</h3>
        {% endif %}
      </section>

      <section>
        <h3>Recent Book Reviews:</h3>

        {% for reviewer in reviewers %}
          <article>
            <h4><a href="{% url 'book_reviews:book' reviewer.book.id %}">{{ reviewer.book.title }}</a></h4>
            <p>{{ reviewer.review.rating }}</p>
            <p><a style="text-decoration:underline;" href="">{{ reviewer.user.first_name }}</a> says: {{ reviewer.review.review }}</p>
            <p>Posted on {{ reviewer.review.created_at }}</p>
          </article>
        {% endfor %}
      </section>
    </div>
  </body>
</html>