main/apps/book_reviews/urls.py
from django.conf.urls import url
from . import views

app_name = 'book_reviews'
urlpatterns = [
    url(r'^$', views.index, name='index'),
]

main/apps/login_reg/urls.py
from django.conf.urls import url
from . import views

app_name = 'login_reg'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^login$', views.login, name='login'),
    url(r'^logout$', views.logout, name='logout'),
    url(r'^register$', views.register, name='register'),
    url(r'^success/(?P<id>\d+)$', views.success, name='success'),
    url(r'^delete/(?P<id>\d+)$', views.delete, name='delete'),
]

main/main/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^login_reg/', include('apps.login_reg.urls', namespace='login_reg')),
    url(r'^book_reviews/', include('apps.book_reviews.urls', namespace='book_reviews')),
    url(r'^', include('apps.login_reg.urls', namespace='login_reg')),
]

main/apps/book_reviews/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

main/apps/login_reg/models.py
from __future__ import unicode_literals

from django.db import models
import bcrypt
import re

EMAIL_REGEX = re.compile(r'^[a-zA-Z0-9\.\+_-]+@[a-zA-Z0-9\._-]+\.[a-zA-Z]*$')

# Create your models here.
class UserManager(models.Manager):
    def login(self, postData):
        email = postData['email']
        password = postData['password']

        alerts = []

        try:
            user = User.objects.get(email=email)
        except:
            print ('EMAIL NOT REGISTERED')
            alerts.append('The email address "{}" is either incorrect or has not been registered.'.format(email))
            return (False, alerts)
        else:
            if email == user.email:
                if bcrypt.hashpw(password.encode(), user.pw_hashed.encode()) == user.pw_hashed:
                    # print ('it matches', user.id)
                    return (True, 'back, {}! You have successfully logged in.'.format(user.first_name), user.id)
                else:
                    # print ('no pw match')
                    alerts.append('The password entered is incorrect. Please try again.')

            if alerts:
                return (False, alerts)


    def register(self, postData):
        # grabs user input from registration form
        first_name = str(postData['first_name'])
        last_name = str(postData['last_name'])
        email = postData['email']
        password = postData['password']
        pw_verify = postData['pw_verify']

        alerts = []

        if len(first_name) < 2:
            alerts.append('First name must be at least 2 characters in length.')
        elif not str.isalpha(first_name):
            alerts.append('First name must contain letters only.')

        if len(last_name) < 2:
            alerts.append('Last name must be at least 2 characters in length.')
        elif not str.isalpha(last_name):
            alerts.append('Last name must contain letters only.')

        if len(email) < 1:
            alerts.append('Email cannot be left blank.')
        elif not EMAIL_REGEX.match(email):
            alerts.append('Invalid email address.')

        if len(password) < 8:
            alerts.append('Password must be at least 8 characters in length.')
        elif password != pw_verify:
            alerts.append('Passwords do not match.')

        if alerts:
            return (False, alerts)

        else:
            pw_hashed = bcrypt.hashpw(password.encode(), bcrypt.gensalt())
            user = User.objects.create(first_name=first_name, last_name=last_name, email=email, pw_hashed=pw_hashed)
            return (True, 'aboard, {}! You have successfully registered.'.format(first_name), user.id)


class User(models.Model):
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    email = models.EmailField(max_length=255)
    pw_hashed = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    userManager = UserManager()
    objects = models.Manager()

main/apps/book_reviews/views.py
from django.shortcuts import render, redirect, HttpResponse
from django.core.urlresolvers import reverse

# Create your views here.
def index(request):
    return render(request, 'book_reviews/index.html')

main/apps/login_reg/views.py
# login_reg
from django.shortcuts import render, redirect, HttpResponse
from .models import User
from django.contrib import messages
from django.core.urlresolvers import reverse

# Create your views here.
def index(request):
    print (User.objects.all())
    context = {
        'users':User.objects.all()
    }
    return render(request, 'login_reg/index.html', context)


def login(request):
    if request.method == "POST":
        verify = User.userManager.login(request.POST)

        if verify[0] == False:
            for alert in verify[1]:
                messages.add_message(request, messages.INFO, alert)
            return redirect(reverse('login_reg:index'))

        elif verify[0] == True:
            request.session['success'] = verify[1]
            id = verify[2]
            return redirect(reverse('login_reg:success', kwargs={'id':id}))

        else:
            request.session.clear()
            return redirect(reverse('login_reg:index'))


def register(request):
    if request.method == "POST":
        verify = User.userManager.register(request.POST)

        if verify[0] == False:
            for alert in verify[1]:
                messages.add_message(request, messages.INFO, alert)
            return redirect(reverse('login_reg:index'))

        elif verify[0] == True:
            request.session['success'] = verify[1]
            id = verify[2]
            return redirect(reverse('login_reg:success', kwargs={'id':id}))
        else:
            request.session.clear()
            return redirect(reverse('login_reg:index'))


def success(request, id):
    context = {
        'user':User.objects.get(id=id)
    }
    return render(request, 'login_reg/success.html', context)


def logout(request):
    request.session.clear()
    return redirect(reverse('login_reg:index'))


def delete(request, id):
    alerts = []
    if request.method == "POST":
        user = User.objects.get(id=id)
        alerts.append('The account registered under the email address "{}" has been deleted.'.format(user.email))
        user.delete()
        return redirect(reverse('login_reg:index'))

main/apps/book_reviews/templates/book_reviews/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <title>Book Reviews</title>
    <meta name="description" content="Coding Dojo, Python II, Django II, Belt Reviewer Assignment">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link rel="stylesheet" type="text/css" href="">
  </head>
  <body>
    <div class="container">
      <header class="page-header">
        <h1>Book Reviews <small>placeholder</small></h1>
      </header>
    </div>
  </body>
</html>

main/apps/login_reg/templates/login_reg/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <title>Login and Registration</title>
    <meta name="description" content="Coding Dojo, Python II, Django II, Login and Registration Assignment">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'login_reg/css/style.css' %}">
  </head>
  <body>
    <div class="container">
      <nav>
        <a class="btn btn-link" style="float:right;" role="button" href="/">back to landing page</a>
      </nav>
      <header class="page-header">
        <h1>Login and Registration <small>(with Django)</small></h1>
      </header>

      <!-- {% for user in users %}
        <p>{{ user.id }} | {{ user.first_name }} | {{ user.last_name }} | {{ user.email }} | {{ user.pw_hashed }}</p>
      {% endfor %} -->
  <!-- flash messages section -->
      <section>
        {% if messages %}
          <div class="alert alert-danger">
          {% for alert in messages %}
            <p {% if messages.tags %} class="messages.tags" {% endif %}>{{ alert }}</p>
          {% endfor %}
        </div>
        {% endif %}
      </section>

  <!-- forms section -->
      <section>
        <article>
          <h3>Register</h3>
          <form class="form-horizontal" action="{% url 'login_reg:register' %}" method="POST">
            {% csrf_token %}
            <div class="form-group">
              <label class="control-label">First Name:</label>
              <input class="form-control" type="text" name="first_name">
            </div>
            <div class="form-group">
              <label class="control-label">Last Name:</label>
              <input class="form-control" type="text" name="last_name">
            </div>
            <div class="form-group">
              <label class="control-label">Email:</label>
              <input class="form-control" type="text" name="email">
            </div>
            <div class="form-group">
              <label class="control-label">Password:</label>
              <input class="form-control" type="text" name="password">
            </div>
            <div class="form-group">
              <label class="control-label">Confirm pw:</label>
              <input class="form-control" type="text" name="pw_verify">
            </div>
            <div class="form-group">
              <input class="btn btn-primary" type="submit" value="Register">
            </div>
          </form>
        </article>

        <article>
          <h3>Login</h3>
          <form class="form-horizontal" action="{% url 'login_reg:login' %}" method="POST">
            {% csrf_token %}
            <div class="form-group">
              <label class="control-label">Email:</label>
              <input class="form-control" type="text" name="email">
            </div>
            <div class="form-group">
              <label class="control-label">Password:</label>
              <input class="form-control" type="text" name="password">
            </div>
            <div class="form-group">
              <input class="btn btn-primary" type="submit" value="Login">
            </div>
          </form>
        </article>
      </section>

    </div>
  </body>
</html>

main/apps/login_reg/templates/login_reg/success.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <title>Login and Registration</title>
    <meta name="description" content="Coding Dojo, Python II, Django II, Login and Registration Assignment">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'login_reg/css/style.css' %}">
  </head>
  <body>
    <div class="container">
      <nav>
        <form action="{% url 'login_reg:delete' user.id %}" method="POST">
          {% csrf_token %}
          <input class="btn btn-link" type="submit" value="delete account">
          <a class="btn btn-link" href="{% url 'login_reg:logout' %}" role="button">logout</a>
        </form>
      </nav>
      <header class="page-header">
        <h1>Login and Registration <small>Success Page</small></h1>
      </header>

      <section>
        {% if request.session.success %}
          <h3>Welcome {{ request.session.success }}</h3>
        {% endif %}

        <!-- {{ user.id }} {{ user.first_name }} -->
      </section>
    </div>
  </body>
</html>